### ISSUE TITLE
``npm test`` fails with JSON parse error

### ISSUE THREAD

**Issue by liamdennehy** [w3c-dvcg/http-signatures-test-suite#6]
In testing #5 at b7a8b32, ``npm test`` with a simple ``cat`` or any other command generates the linked error. ``strace`` does not reveal any file read by the process that appears corrupt.

https://pastebin.com/yD9gD5NF

Summary:
```
/home/user/src/http-signatures-test-suite/node_modules/yargs/yargs.js:1163
      else throw err
           ^
 
SyntaxError: /home/user/src/http-signatures-test-suite/config.json: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:672:27)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/src/http-signatures-test-suite/test/latest/10-canonicalize.js:1:78)
```

**Comment by liamdennehy** [comment]
Well the answer appears to be right in front of me: The offending json is the file provided in this package in ``master``. The comments are not valid JSON, but the instructions in master contain nothing on stripping them. I see the current example config has stripped them.

Apologies for the noise :)
